"""Add MealSchedule model

Revision ID: 6924f5a06d74
Revises: b8f88465c7fa
Create Date: 2025-12-25 00:16:03.270713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6924f5a06d74'
down_revision = 'b8f88465c7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_unit', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('goal_weight', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('height_unit', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('estimated_daily_steps', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('workout_difficulty', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=False))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('fitness_goal',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('fitness_goal',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('location')
        batch_op.drop_column('workout_difficulty')
        batch_op.drop_column('estimated_daily_steps')
        batch_op.drop_column('height_unit')
        batch_op.drop_column('goal_weight')
        batch_op.drop_column('weight_unit')

    # ### end Alembic commands ###
