"""Add meal schedules table

Revision ID: b8f88465c7fa
Revises: 0abd741f6ced
Create Date: 2025-12-24 00:24:03.485807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f88465c7fa'
down_revision = '0abd741f6ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_calories', sa.Integer(), nullable=True),
    sa.Column('daily_protein', sa.Integer(), nullable=True),
    sa.Column('daily_carbs', sa.Integer(), nullable=True),
    sa.Column('daily_fat', sa.Integer(), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('goal_weight', sa.Float(), nullable=True),
    sa.Column('days_to_goal', sa.Integer(), nullable=True),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.Column('weekly_plan', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('generation_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_schedules')
    # ### end Alembic commands ###
